#!/bin/bash

C_OPT=0
DIR=`pwd`
VERSION="0.1Alpha"

HOST=""
PORT=""
INPUT=""
OUTPUT=""
ROTATE=""
MEAN="False"

while [ "$1" != "" ]; 
do
   case $1 in
    -h | --host )
        shift
        HOST="$1"
        ;;
    -p | --port )
        shift
        PORT="$1"
        ;;
    -i | --input )
        shift
        INPUT="$1"
        ;;
    -o | --output )
        shift
        OUTPUT="$1"
        ;;
    -r | --rotate )
        shift
        ROTATE="$1"
        ;;
    -m | --mean )
        MEAN="True"
        ;;                                        
    * ) 
        echo "Invalid option: $1"
        exit
       ;;
  esac
  shift
done

python ./python/image_client.py --host $HOST --port $PORT --input $INPUT --output $OUTPUT --rotate $ROTATE --mean $MEAN